// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw8lAucUhKlvIGdfE6BZJL4WA2s4sCitE',
    appId: '1:995050283484:web:1dfa59ac5797560dbe2f19',
    messagingSenderId: '995050283484',
    projectId: 'pekimedia-539fa',
    authDomain: 'pekimedia-539fa.firebaseapp.com',
    storageBucket: 'pekimedia-539fa.appspot.com',
    measurementId: 'G-7002SCRDD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_V6tnEpSrpal6mFmhZHW5TB6P2U79LfY',
    appId: '1:995050283484:android:67bf1a36556b30bdbe2f19',
    messagingSenderId: '995050283484',
    projectId: 'pekimedia-539fa',
    storageBucket: 'pekimedia-539fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHbXYJHouDbrHWTNEvCHhwApy9HHZqww',
    appId: '1:995050283484:ios:8633349ecee62d8ebe2f19',
    messagingSenderId: '995050283484',
    projectId: 'pekimedia-539fa',
    storageBucket: 'pekimedia-539fa.appspot.com',
    iosBundleId: 'com.example.pekiMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHbXYJHouDbrHWTNEvCHhwApy9HHZqww',
    appId: '1:995050283484:ios:8633349ecee62d8ebe2f19',
    messagingSenderId: '995050283484',
    projectId: 'pekimedia-539fa',
    storageBucket: 'pekimedia-539fa.appspot.com',
    iosBundleId: 'com.example.pekiMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw8lAucUhKlvIGdfE6BZJL4WA2s4sCitE',
    appId: '1:995050283484:web:67d97b32f30f665cbe2f19',
    messagingSenderId: '995050283484',
    projectId: 'pekimedia-539fa',
    authDomain: 'pekimedia-539fa.firebaseapp.com',
    storageBucket: 'pekimedia-539fa.appspot.com',
    measurementId: 'G-3BB4ETLX2F',
  );
}
